// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtI5Ixe415JI9Hwy6Q9J1Ox4uB5x7JpUs',
    appId: '1:826709313501:web:2b9f0c8989cd51e5fe5834',
    messagingSenderId: '826709313501',
    projectId: 'worksphereai',
    authDomain: 'worksphereai.firebaseapp.com',
    storageBucket: 'worksphereai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZpA-FOWn_Ggh2KdHcL4BLOz6-LL4qCFo',
    appId: '1:826709313501:android:cc6053f8a968d4fafe5834',
    messagingSenderId: '826709313501',
    projectId: 'worksphereai',
    storageBucket: 'worksphereai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjqUpk0GAmRyEPjzZtG25GseGpe11VMA',
    appId: '1:826709313501:ios:5259a71fec5e6c31fe5834',
    messagingSenderId: '826709313501',
    projectId: 'worksphereai',
    storageBucket: 'worksphereai.firebasestorage.app',
    iosBundleId: 'com.example.workSphereAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjqUpk0GAmRyEPjzZtG25GseGpe11VMA',
    appId: '1:826709313501:ios:5259a71fec5e6c31fe5834',
    messagingSenderId: '826709313501',
    projectId: 'worksphereai',
    storageBucket: 'worksphereai.firebasestorage.app',
    iosBundleId: 'com.example.workSphereAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtI5Ixe415JI9Hwy6Q9J1Ox4uB5x7JpUs',
    appId: '1:826709313501:web:e2e2b882f2b90e3cfe5834',
    messagingSenderId: '826709313501',
    projectId: 'worksphereai',
    authDomain: 'worksphereai.firebaseapp.com',
    storageBucket: 'worksphereai.firebasestorage.app',
  );
}
